[package]
name = "power-graph"
version = "0.6.0"
authors = ["Dmitriy Pogretskiy <dpogretskiy@gmail.com>"]

[dependencies]
winapi = { version = "0.3", features = ["errhandlingapi", "handleapi", "memoryapi"] }
ggez = "0.4"

[profile.release]
debug = true
