[package]
name = "pcars2sample"
version = "0.1.0"
authors = ["Dmitriy Pogretskiy <dpogretskiy@gmail.com>"]

[dependencies]
memmap = "0.6.2"
winapi = { version = "0.3", features = ["errhandlingapi"] }
ggez = "0.4"

[profile.release]
debug = true
